Repository speced/respec, pull requests merged in 2020-06, with the labels that each got.

#2932 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#2978 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#2983 fix(w3c/sotd): require data-deliverer for IG Notes
  src/w3c/templates/sotd.js
Labels: enhancement

#2987 chore: update dependencies, fix outdated tests
  .eslintrc.json
  package-lock.json
  package.json
  tests/spec/core/highlight-spec.js
  tests/spec/core/xref-spec.js
Labels: legacy
