Repository speced/respec, pull requests merged in 2021-11, with the labels that each got.

#3848 Add support for various 2021 W3C templates
  src/core/render-biblio.js
  src/w3c/defaults.js
  src/w3c/group.js
  src/w3c/headers.js
  src/w3c/l10n.js
  src/w3c/seo.js
  src/w3c/style.js
  src/w3c/templates/headers.js
  src/w3c/templates/sotd.js
  tests/spec/core/exporter-spec.js
  tests/spec/core/linter-rules/a11y-spec.js
  tests/spec/core/override-configuration-spec.js
  tests/spec/geonovum/style-spec.js
  tests/spec/w3c/group-spec.js
  tests/spec/w3c/headers-spec.js
  tests/spec/w3c/style-spec.js
Labels: enhancement, DONT MERGE, High priority

#3882 chore(deps): update dependencies
  package-lock.json
  package.json
Labels: dependencies

#3883 Fixes Note and REC stability boilerplates
  src/w3c/templates/sotd.js
  tests/spec/w3c/headers-spec.js
Labels: bug
